# @package _global_
data:
  data_path: /home/dhkim/mimesys_training_data/v1
  action_path: /home/dhkim/mimesys_training_data/v1
  test_data_path: /home/dhkim/mimesys/artifacts/traces
  aug_factor: 5
  intra_only_aug: true
  high_io_aug_factor: 1
  io_raw_threshold: 1000.0
  batch_size: 1024
  dataset_size: 100
  test_batch_size: 1
  test_machines:
  - c220g2-011110.wisc.cloudlab.us
log:
  project_name: mimesys_pretrain
  run_name: diffusion/mimesys_pretrain_v1
profiler:
  user_name: dhkim
  private_key_path: /home/dhkim/.ssh/id_rsa
  my_hostname: <FILL_IN_HOSTNAME>
  destination_path: /home/dhkim/mimesys_profiling_results
  validation_destination_path: /home/dhkim/mimesys_validation_results
model:
  autoencoder:
    hidden_dim: 16
    input_dim: 23
    latent_dim: 10
  context:
    action_dim: 33
    dropout: 0.1
    hidden_dim: 256
    input_dim: 23
    num_heads: 4
    num_layers: 6
  diffusion:
    cfg_args:
      cfg_drop_prob: 0.1
      cfg_guide_w: 3
    n_timesteps: 25
  mlp:
    dropout: 0.1
    hidden_dim: 128
    input_dim: 480
  transformer:
    dropout: 0.1
    hidden_dim: 256
    input_dim: 500
    num_heads: 4
    num_layers: 6
    output_dim: 25
  unet:
    input_dim: 20
train:
  async_validation: true
  callbacks:
    checkpoint:
      dirpath: diffusion/mimesys_pretrain_v1
      every_n_epochs: 500
      monitor: epoch
  ddpo:
    num_batches_per_episode: 46
    num_inner_epochs: 1
    reward_type: profiling
  optim:
    lr: 1e-4
  prev_state_lambda: 0.0
  run_test: false
  run_train: true
  trainer:
    check_val_every_n_epoch: 500
    devices: 1
    max_epochs: 2000
    trainer_model_name: MimesysTrainer
  use_rl: false
